=== linvald/ERToEJB/resources/ERSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by jes (litu) -->
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="attributeType">
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="value" use="required"/>
	</xs:complexType>
	<xs:complexType name="entityType">
		<xs:sequence>
			<xs:element name="attribute" type="attributeType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:element name="ermodel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="keystrategy" type="keystrategyType"/>
				<xs:element name="entity" type="entityType" maxOccurs="unbounded"/>
				<xs:element name="relation" type="relationType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="keystrategyType">
		<xs:attribute name="strategy" type="xs:string" use="required"/>
		<xs:attribute name="generate" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="relationType">
		<xs:sequence>
			<xs:element name="source" type="sourceType"/>
			<xs:element name="target" type="targetType"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="direction" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="bidirectional"/>
					<xs:enumeration value="unidirectional"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="sourceType">
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="cardinality" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="many"/>
					<xs:enumeration value="one"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="cardinality" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="many"/>
					<xs:enumeration value="one"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== linvald/ERToEJB/resources/relations.xml
<?xml version="1.0" encoding="UTF-8"?>
<ermodel name="RelationTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ERSchema.xsd">
	<keystrategy strategy="autoincrement" generate="true"/>
	<entity name="Left">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Right">
		<attribute name="myInt" value="java.lang.Integer"/>
		<attribute name="myFriends" value="java.util.ArrayList"/>
	</entity>
	<entity name="One">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Two">
		<attribute name="myInt" value="java.lang.Integer"/>
		<attribute name="myFriends" value="java.util.ArrayList"/>
	</entity>
	<entity name="Ying">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Yang">
		<attribute name="myInt" value="java.lang.Integer"/>
		<attribute name="myFriends" value="java.util.ArrayList"/>
	</entity>
	<entity name="Sort">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Hvid">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="God">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Ond">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Java">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<entity name="Csharp">
		<attribute name="myString" value="java.lang.String"/>
		<attribute name="myThings" value="java.util.ArrayList"/>
	</entity>
	<relation name="left_has_right_one_2_one_uni" direction="unidirectional">
		<source name="Left" cardinality="one"/>
		<target name="Right" cardinality="one"/>
	</relation>
	<relation name="one_has_many_twos_uni" direction="unidirectional">
		<source name="One" cardinality="one"/>
		<target name="Two" cardinality="many"/>
	</relation>
	<relation name="many_yings_has_yangs" direction="unidirectional">
		<source name="Ying" cardinality="many"/>
		<target name="Yang" cardinality="many"/>
	</relation>
	<relation name="sort_has_hvid_bi_one_one" direction="bidirectional">
		<source name="Sort" cardinality="one"/>
		<target name="Hvid" cardinality="one"/>
	</relation>
	<relation name="god_has_ond_bi_one_many" direction="bidirectional">
		<source name="God" cardinality="one"/>
		<target name="Ond" cardinality="many"/>
	</relation>
	<relation name="javas_has_csharps_bi_many_many" direction="bidirectional">
		<source name="Java" cardinality="many"/>
		<target name="Csharp" cardinality="many"/>
	</relation>
</ermodel>
